# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 13:09
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activity_Monitor', '0002_auto_20170123_0856'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='age',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='user',
            name='hospitalID',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
