# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 13:40
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Activity_Monitor', '0004_auto_20170208_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('hospitalID', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30, null=True, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('salt', models.CharField(max_length=10)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('employee_agreement_file', models.FileField(blank=True, upload_to='agreement_files')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now_add=True)),
                ('SystemUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Activity_Monitor.SystemUser')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='users',
            name='SystemUser',
        ),
        migrations.AlterField(
            model_name='practitioner',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Activity_Monitor.User'),
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
